apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 100xdevs/antidevs-frontend:6fb93cea8dda69f391142da3ff52e7ab9518f408
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: CLERK_SECRET_KEY
            - name: NEXT_PUBLIC_BACKEND_URL
              value: https://primary-backend.antidevs.com
            - name: NEXT_PUBLIC_K8S_ORCHESTRATOR_URL
              value: https://k8s-orchestrator.antidevs.com
