apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-backend
  template:
    metadata:
      labels:
        app: primary-backend
    spec:
      containers:
        - name: primary-backend
          image: 100xdevs/antidevs-primary-backend:latest
          ports:
            - containerPort: 9090
          env:
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: primary-backend-secret
                  key: JWT_PUBLIC_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: primary-backend-secret
                  key: DATABASE_URL
            