name: Docker Publish WS Relay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ws-relayer
        uses: docker/build-push-action@v5
        with:
          context: ./mobile-magic
          file: ./mobile-magic/docker/Dockerfile.ws-relayer
          push: true
          tags: 100xdevs/antidevs-ws-relayer:${{ github.sha }}
