import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { Appbar } from "@/components/Appbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
	variable: "--font-space-grotesk",
	subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
			<html lang="en">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<ClerkProvider>
						<body
							className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} antialiased`}
						>
							<main className="relative w-full overflow-hidden">
								<div className="absolute -top-56 -right-28 size-96 md:w-3xl md:-right-64 md:-top-64 -z-30 rounded-full bg-radial from-red-00 to-red-500 blur-3xl" />
								<Appbar />
								{children}
							</main>
							<Toaster />
						</body>
					</ClerkProvider>
				</ThemeProvider>
			</html>
		);
}
